/**
 * Base interface for all OpenCode agents
 */
export interface Agent {
  /** Agent identifier */
  id: string;
  
  /** Agent name */
  name: string;
  
  /** Agent description */
  description: string;
  
  /** Process a user request */
  process(request: AgentRequest): Promise<AgentResponse>;
  
  /** Get available tools for this agent */
  getTools(): Tool[];
}

/**
 * Request structure for agent processing
 */
export interface AgentRequest {
  /** User's input message or task */
  message: string;
  
  /** Context from previous interactions */
  context?: AgentContext;
  
  /** Additional metadata */
  metadata?: Record<string, any>;
}

/**
 * Response structure from agent processing
 */
export interface AgentResponse {
  /** Response message */
  message: string;
  
  /** Whether the task was completed successfully */
  success: boolean;
  
  /** Updated context */
  context?: AgentContext;
  
  /** Tool calls made during processing */
  toolCalls?: ToolCall[];
  
  /** Any artifacts generated */
  artifacts?: Artifact[];
}

/**
 * Context maintained across agent interactions
 */
export interface AgentContext {
  /** Conversation history */
  history?: Message[];
  
  /** Working directory or file paths */
  workingDirectory?: string;
  
  /** Session-specific data */
  sessionData?: Record<string, any>;
}

/**
 * Message in conversation history
 */
export interface Message {
  role: 'user' | 'agent' | 'system';
  content: string;
  timestamp: Date;
}

/**
 * Tool definition for agent capabilities
 */
export interface Tool {
  /** Tool identifier */
  name: string;
  
  /** Tool description */
  description: string;
  
  /** Parameters schema */
  parameters: ToolParameters;
  
  /** Execute the tool */
  execute(params: Record<string, any>): Promise<any>;
}

/**
 * Tool parameters schema
 */
export interface ToolParameters {
  type: 'object';
  properties: Record<string, ParameterDefinition>;
  required?: string[];
}

/**
 * Parameter definition in tool schema
 */
export interface ParameterDefinition {
  type: string;
  description: string;
  enum?: string[];
  default?: any;
}

/**
 * Tool call record
 */
export interface ToolCall {
  tool: string;
  parameters: Record<string, any>;
  result: any;
  timestamp: Date;
}

/**
 * Artifact generated by agent
 */
export interface Artifact {
  type: 'file' | 'code' | 'data' | 'report';
  name: string;
  content: string;
  metadata?: Record<string, any>;
}

/**
 * Configuration for agent behavior
 */
export interface AgentConfig {
  /** Agent type */
  type: 'primary' | 'subagent';
  
  /** System prompt path */
  systemPromptFile?: string;
  
  /** Available tools */
  tools?: string[];
  
  /** Maximum iterations */
  maxIterations?: number;
  
  /** Enable debug logging */
  debug?: boolean;
}
